
export type Question = {
  questionText: string;
  answerOptions: string[];
  correctAnswer: string;
};

export type TopicQuestions = Record<string, Record<number, Question[]>>;


// Note: Ensure there are enough questions for each level. The current system pulls 10 questions.
export const quizQuestions: TopicQuestions = {
  alphabets: {
    1: [
      { questionText: "What is this letter: 'A'?", answerOptions: ["A", "B", "C", "D"], correctAnswer: "A" },
      { questionText: "What comes after 'C'?", answerOptions: ["B", "D", "E", "F"], correctAnswer: "D" },
      { questionText: "Find the letter 'E'.", answerOptions: ["F", "E", "G", "H"], correctAnswer: "E" },
      { questionText: "Which letter is for 'Apple'?", answerOptions: ["A", "B", "C", "D"], correctAnswer: "A" },
      { questionText: "What is the first letter of the alphabet?", answerOptions: ["Z", "A", "B", "C"], correctAnswer: "A" },
      { questionText: "What is this letter: 'B'?", answerOptions: ["D", "C", "B", "A"], correctAnswer: "B" },
      { questionText: "Which letter comes before 'C'?", answerOptions: ["A", "D", "B", "E"], correctAnswer: "B" },
      { questionText: "Find the letter 'F'.", answerOptions: ["E", "G", "F", "H"], correctAnswer: "F" },
      { questionText: "Which letter is for 'Cat'?", answerOptions: ["D", "C", "A", "B"], correctAnswer: "C" },
      { questionText: "What is the last letter of the alphabet?", answerOptions: ["Y", "X", "W", "Z"], correctAnswer: "Z" },
    ],
    2: [
      { questionText: "What is the lowercase for 'A'?", answerOptions: ["a", "b", "c", "d"], correctAnswer: "a" },
      { questionText: "Which of these is a vowel?", answerOptions: ["B", "C", "D", "A"], correctAnswer: "A" },
      { questionText: "What comes between 'G' and 'I'?", answerOptions: ["F", "H", "J", "K"], correctAnswer: "H" },
      { questionText: "Which letter is NOT a vowel?", answerOptions: ["A", "E", "I", "F"], correctAnswer: "F" },
      { questionText: "Find the missing letter: A, B, C, __, E", answerOptions: ["F", "G", "D", "H"], correctAnswer: "D" },
      { questionText: "What is the uppercase for 'b'?", answerOptions: ["A", "C", "B", "D"], correctAnswer: "B" },
      { questionText: "Which word starts with 'H'?", answerOptions: ["Apple", "Ball", "Hat", "Dog"], correctAnswer: "Hat" },
      { questionText: "How many letters are in the word 'SUN'?", answerOptions: ["2", "3", "4", "5"], correctAnswer: "3" },
      { questionText: "What is the sound of the letter 'S'?", answerOptions: ["sss", "tuh", "buh", "cuh"], correctAnswer: "sss" },
      { questionText: "Which letter rhymes with 'tree'?", answerOptions: ["A", "B", "C", "D"], correctAnswer: "B" },
    ],
    3: [
      { questionText: "Unscramble the word: 'atc'", answerOptions: ["cat", "act", "tac", "atc"], correctAnswer: "cat" },
      { questionText: "What is the middle letter of 'DOG'?", answerOptions: ["D", "O", "G", "A"], correctAnswer: "O" },
      { questionText: "Find the word that does NOT start with 'B'.", answerOptions: ["Ball", "Bat", "Car", "Boy"], correctAnswer: "Car" },
      { questionText: "How many vowels are in the word 'APPLE'?", answerOptions: ["1", "2", "3", "4"], correctAnswer: "2" },
      { questionText: "Which two letters make the 'sh' sound?", answerOptions: ["S and H", "S and C", "C and H", "S and S"], correctAnswer: "S and H" },
      { questionText: "What is the plural of 'cat'?", answerOptions: ["cates", "caties", "cats", "cato"], correctAnswer: "cats" },
      { questionText: "Complete the sequence: M, N, O, __", answerOptions: ["P", "Q", "L", "K"], correctAnswer: "P" },
      { questionText: "Which word is longer: 'ANT' or 'ELEPHANT'?", answerOptions: ["ANT", "ELEPHANT", "Same", "None"], correctAnswer: "ELEPHANT" },
      { questionText: "What is the opposite of 'UP'?", answerOptions: ["IN", "ON", "DOWN", "OUT"], correctAnswer: "DOWN" },
      { questionText: "Find the lowercase for 'Q'.", answerOptions: ["p", "d", "b", "q"], correctAnswer: "q" },
    ],
    4: [
      { questionText: "Which word rhymes with 'house'?", answerOptions: ["horse", "mouse", "home", "hat"], correctAnswer: "mouse" },
      { questionText: "What is the first letter of 'Zebra'?", answerOptions: ["Z", "A", "Y", "B"], correctAnswer: "Z" },
      { questionText: "Arrange these letters alphabetically: B, A, C", answerOptions: ["B, A, C", "C, B, A", "A, B, C", "A, C, B"], correctAnswer: "A, B, C" },
      { questionText: "What do you add to 'book' to make it mean more than one?", answerOptions: ["-es", "-ing", "-s", "-ed"], correctAnswer: "-s" },
      { questionText: "Find the 'silent' letter in 'know'.", answerOptions: ["k", "n", "o", "w"], correctAnswer: "k" },
      { questionText: "Which word is spelled correctly?", answerOptions: ["aple", "appel", "apple", "appl"], correctAnswer: "apple" },
      { questionText: "What is the opposite of 'BIG'?", answerOptions: ["TALL", "SMALL", "WIDE", "LONG"], correctAnswer: "SMALL" },
      { questionText: "How many syllables are in 'banana'?", answerOptions: ["1", "2", "3", "4"], correctAnswer: "3" },
      { questionText: "Which of these is a compound word?", answerOptions: ["Rainbow", "Pretty", "Happy", "Jumping"], correctAnswer: "Rainbow" },
      { questionText: "What is the past tense of 'run'?", answerOptions: ["runned", "ran", "running", "runs"], correctAnswer: "ran" },
    ],
    5: [
      { questionText: "Identify the adjective in: 'The red car is fast.'", answerOptions: ["The", "red", "car", "fast"], correctAnswer: "red" },
      { questionText: "Which sentence is a question?", answerOptions: ["I like ice cream.", "What is your name?", "Go to your room.", "That is a big dog!"], correctAnswer: "What is your name?" },
      { questionText: "What is a synonym for 'happy'?", answerOptions: ["Sad", "Angry", "Joyful", "Tired"], correctAnswer: "Joyful" },
      { questionText: "What is an antonym for 'hot'?", answerOptions: ["Warm", "Cold", "Spicy", "Sunny"], correctAnswer: "Cold" },
      { questionText: "Complete the analogy: 'Puppy is to dog as kitten is to ___.'", answerOptions: ["cat", "cub", "puppy", "animal"], correctAnswer: "cat" },
      { questionText: "Identify the verb in: 'Birds fly in the sky.'", answerOptions: ["Birds", "fly", "in", "sky"], correctAnswer: "fly" },
      { questionText: "What does the prefix 'un-' mean in 'unhappy'?", answerOptions: ["very", "not", "again", "before"], correctAnswer: "not" },
      { questionText: "Which word means 'to look quickly'?", answerOptions: ["Stare", "Gaze", "Glance", "Watch"], correctAnswer: "Glance" },
      { questionText: "What punctuation mark ends a sentence that shows excitement?", answerOptions: [".", ",", "?", "!"], correctAnswer: "!" },
      { questionText: "Unscramble the sentence: 'likes to play She'", answerOptions: ["Play to she likes", "She likes to play", "Likes she to play", "To play she likes"], correctAnswer: "She likes to play" },
    ],
  },
  numbers: {
    1: [
      { questionText: "Which number is this: '1'?", answerOptions: ["One", "Two", "Three", "Four"], correctAnswer: "One" },
      { questionText: "How many suns are in the sky?", answerOptions: ["1", "2", "3", "4"], correctAnswer: "1" },
      { questionText: "What comes after 3?", answerOptions: ["2", "4", "5", "6"], correctAnswer: "4" },
      { questionText: "Which number is bigger: 2 or 4?", answerOptions: ["2", "4", "Same", "None"], correctAnswer: "4" },
      { questionText: "Count the dots: (•••)", answerOptions: ["2", "3", "4", "5"], correctAnswer: "3" },
      { questionText: "What comes before 2?", answerOptions: ["1", "3", "4", "0"], correctAnswer: "1" },
      { questionText: "Which number is smaller: 5 or 3?", answerOptions: ["5", "3", "Same", "None"], correctAnswer: "3" },
      { questionText: "Find the number 'Five'.", answerOptions: ["3", "4", "5", "6"], correctAnswer: "5" },
      { questionText: "How many wheels does a bicycle have?", answerOptions: ["1", "2", "3", "4"], correctAnswer: "2" },
      { questionText: "Count the stars: ★ ★ ★ ★", answerOptions: ["3", "4", "5", "6"], correctAnswer: "4" },
    ],
    2: [
      { questionText: "What is 2 + 1?", answerOptions: ["2", "3", "4", "5"], correctAnswer: "3" },
      { questionText: "What is 3 - 1?", answerOptions: ["1", "2", "3", "4"], correctAnswer: "2" },
      { questionText: "Which number is missing: 5, 6, __, 8?", answerOptions: ["4", "7", "9", "10"], correctAnswer: "7" },
      { questionText: "How do you write 'Ten'?", answerOptions: ["10", "11", "9", "1"], correctAnswer: "10" },
      { questionText: "What is 1 more than 9?", answerOptions: ["8", "9", "10", "11"], correctAnswer: "10" },
      { questionText: "If you have 3 cookies and eat 1, how many are left?", answerOptions: ["1", "2", "3", "4"], correctAnswer: "2" },
      { questionText: "Which number comes after 12?", answerOptions: ["11", "13", "14", "10"], correctAnswer: "13" },
      { questionText: "Count backwards from 5.", answerOptions: ["5,4,3,2,1", "1,2,3,4,5", "5,4,2,1,3", "5,3,1,2,4"], correctAnswer: "5,4,3,2,1" },
      { questionText: "What is 5 + 5?", answerOptions: ["8", "9", "10", "11"], correctAnswer: "10" },
      { questionText: "Which number is between 15 and 17?", answerOptions: ["14", "15", "16", "18"], correctAnswer: "16" },
    ],
    3: [
      { questionText: "What is 10 + 5?", answerOptions: ["12", "15", "18", "20"], correctAnswer: "15" },
      { questionText: "What is 8 - 3?", answerOptions: ["4", "5", "6", "7"], correctAnswer: "5" },
      { questionText: "Which is an even number?", answerOptions: ["3", "5", "7", "8"], correctAnswer: "8" },
      { questionText: "Which is an odd number?", answerOptions: ["2", "4", "6", "9"], correctAnswer: "9" },
      { questionText: "Count in 2s: 2, 4, 6, __", answerOptions: ["7", "8", "9", "10"], correctAnswer: "8" },
      { questionText: "What is the number for 'Twenty'?", answerOptions: ["12", "20", "22", "30"], correctAnswer: "20" },
      { questionText: "There are 4 birds. 2 more come. How many now?", answerOptions: ["4", "5", "6", "7"], correctAnswer: "6" },
      { questionText: "Which number is the biggest?", answerOptions: ["11", "19", "9", "15"], correctAnswer: "19" },
      { questionText: "Which number is the smallest?", answerOptions: ["13", "7", "17", "10"], correctAnswer: "7" },
      { questionText: "What is 10 - 10?", answerOptions: ["0", "1", "10", "20"], correctAnswer: "0" },
    ],
    4: [
      { questionText: "What is 3 x 3?", answerOptions: ["6", "8", "9", "12"], correctAnswer: "9" },
      { questionText: "What is half of 10?", answerOptions: ["3", "4", "5", "6"], correctAnswer: "5" },
      { questionText: "Count in 5s: 5, 10, __, 20", answerOptions: ["12", "14", "15", "16"], correctAnswer: "15" },
      { questionText: "What number has 3 tens and 2 ones?", answerOptions: ["23", "32", "30", "20"], correctAnswer: "32" },
      { questionText: "What is 10 divided by 2?", answerOptions: ["2", "4", "5", "8"], correctAnswer: "5" },
      { questionText: "Which is greater: 45 or 54?", answerOptions: ["45", "54", "Same", "None"], correctAnswer: "54" },
      { questionText: "There are 5 apples in 3 baskets. How many total?", answerOptions: ["8", "10", "15", "20"], correctAnswer: "15" },
      { questionText: "Round 27 to the nearest 10.", answerOptions: ["20", "25", "30", "40"], correctAnswer: "30" },
      { questionText: "What is the next even number after 16?", answerOptions: ["17", "18", "19", "20"], correctAnswer: "18" },
      { questionText: "I have 12 candies and give 5 away. How many are left?", answerOptions: ["5", "6", "7", "8"], correctAnswer: "7" },
    ],
    5: [
      { questionText: "What fraction is shaded? (Image of circle half-shaded)", answerOptions: ["1/4", "1/2", "3/4", "1/3"], correctAnswer: "1/2" },
      { questionText: "What is 100 - 25?", answerOptions: ["65", "70", "75", "80"], correctAnswer: "75" },
      { questionText: "What time is it? (Image of clock showing 3:00)", answerOptions: ["12:00", "3:00", "6:00", "9:00"], correctAnswer: "3:00" },
      { questionText: "How many cents are in a dollar?", answerOptions: ["10", "50", "100", "1000"], correctAnswer: "100" },
      { questionText: "What is 7 x 8?", answerOptions: ["49", "54", "56", "63"], correctAnswer: "56" },
      { questionText: "Which is a measurement of length?", answerOptions: ["Kilogram", "Meter", "Liter", "Degree"], correctAnswer: "Meter" },
      { questionText: "What is 521 + 134?", answerOptions: ["655", "654", "645", "555"], correctAnswer: "655" },
      { questionText: "If today is Monday, what is the day after tomorrow?", answerOptions: ["Tuesday", "Wednesday", "Thursday", "Sunday"], correctAnswer: "Wednesday" },
      { questionText: "What is the Roman numeral for 5?", answerOptions: ["I", "V", "X", "L"], correctAnswer: "V" },
      { questionText: "Find the area of a square with a side of 4 cm.", answerOptions: ["8 cm²", "12 cm²", "16 cm²", "20 cm²"], correctAnswer: "16 cm²" },
    ],
  },
  colors: {
    1: [
      { questionText: "What color is a banana?", answerOptions: ["Red", "Yellow", "Blue", "Green"], correctAnswer: "Yellow" },
      { questionText: "What color is the sky on a sunny day?", answerOptions: ["Blue", "Green", "Red", "Black"], correctAnswer: "Blue" },
      { questionText: "What color are most apples?", answerOptions: ["Blue", "Orange", "Red", "Purple"], correctAnswer: "Red" },
      { questionText: "What color is a frog?", answerOptions: ["Red", "Yellow", "Blue", "Green"], correctAnswer: "Green" },
      { questionText: "What color is grass?", answerOptions: ["Yellow", "Blue", "Green", "Pink"], correctAnswer: "Green" },
      { questionText: "What color is a stop sign?", answerOptions: ["Green", "Yellow", "Blue", "Red"], correctAnswer: "Red" },
      { questionText: "What color is the sun?", answerOptions: ["Blue", "Purple", "Yellow", "Black"], correctAnswer: "Yellow" },
      { questionText: "What two colors make Orange?", answerOptions: ["Red & Blue", "Yellow & Blue", "Red & Yellow", "Green & Red"], correctAnswer: "Red & Yellow" },
      { questionText: "What color are carrots?", answerOptions: ["Purple", "Orange", "Blue", "White"], correctAnswer: "Orange" },
      { questionText: "What color is a cloud?", answerOptions: ["White", "Black", "Green", "Red"], correctAnswer: "White" },
    ],
    2: [
      { questionText: "Is a lemon usually yellow or purple?", answerOptions: ["Yellow", "Purple", "Both", "Neither"], correctAnswer: "Yellow" },
      { questionText: "Which of these is a primary color?", answerOptions: ["Green", "Orange", "Purple", "Blue"], correctAnswer: "Blue" },
      { questionText: "What two colors make purple?", answerOptions: ["Red and Yellow", "Blue and Yellow", "Red and Blue", "Green and Red"], correctAnswer: "Red and Blue" },
      { questionText: "What is a 'light' blue called?", answerOptions: ["Navy", "Sky Blue", "Royal Blue", "Dark Blue"], correctAnswer: "Sky Blue" },
      { questionText: "What color is NOT in a rainbow?", answerOptions: ["Red", "Orange", "Yellow", "Brown"], correctAnswer: "Brown" },
      { questionText: "What is the color of a fire truck?", answerOptions: ["Blue", "Yellow", "Red", "Green"], correctAnswer: "Red" },
      { questionText: "Which is a 'cool' color?", answerOptions: ["Red", "Orange", "Yellow", "Blue"], correctAnswer: "Blue" },
      { questionText: "What color is a watermelon on the inside?", answerOptions: ["Green", "Red", "Yellow", "Blue"], correctAnswer: "Red" },
      { questionText: "What does 'transparent' mean?", answerOptions: ["A color", "You can see through it", "Very dark", "Very bright"], correctAnswer: "You can see through it" },
      { questionText: "What color are most trees' leaves in summer?", answerOptions: ["Brown", "Yellow", "Green", "Orange"], correctAnswer: "Green" },
    ],
    3: [
      { questionText: "Which color is a 'warm' color?", answerOptions: ["Blue", "Green", "Purple", "Red"], correctAnswer: "Red" },
      { questionText: "What color do you get if you mix blue and yellow?", answerOptions: ["Green", "Orange", "Purple", "Brown"], correctAnswer: "Green" },
      { questionText: "The color 'pink' is a lighter shade of which color?", answerOptions: ["Red", "Blue", "Yellow", "Green"], correctAnswer: "Red" },
      { questionText: "Which color is often associated with royalty?", answerOptions: ["Orange", "Brown", "Purple", "Gray"], correctAnswer: "Purple" },
      { questionText: "What is the opposite color of black on a color wheel?", answerOptions: ["Gray", "White", "Blue", "Red"], correctAnswer: "White" },
      { questionText: "If you add white to red, what color do you get?", answerOptions: ["Pink", "Orange", "Purple", "Light Red"], correctAnswer: "Pink" },
      { questionText: "What color are emeralds?", answerOptions: ["Red", "Blue", "Green", "Yellow"], correctAnswer: "Green" },
      { questionText: "Which of these is a secondary color?", answerOptions: ["Red", "Yellow", "Blue", "Orange"], correctAnswer: "Orange" },
      { questionText: "The American flag is red, white, and ___.", answerOptions: ["Green", "Yellow", "Blue", "Black"], correctAnswer: "Blue" },
      { questionText: "What color do you get if you mix all primary colors together?", answerOptions: ["White", "Black", "Brown", "Gray"], correctAnswer: "Brown" },
    ],
    4: [
      { questionText: "What does the color red often symbolize?", answerOptions: ["Calmness", "Nature", "Love & Danger", "Sadness"], correctAnswer: "Love & Danger" },
      { questionText: "What are the three primary colors in light (additive)?", answerOptions: ["Red, Yellow, Blue", "Red, Green, Blue", "Cyan, Magenta, Yellow", "Orange, Green, Purple"], correctAnswer: "Red, Green, Blue" },
      { questionText: "What does 'monochromatic' mean in art?", answerOptions: ["Many colors", "Only black and white", "One color with its shades", "Bright colors only"], correctAnswer: "One color with its shades" },
      { questionText: "What is a 'tertiary' color?", answerOptions: ["A mix of a primary and secondary color", "A mix of two primary colors", "A mix of two secondary colors", "A color not in the rainbow"], correctAnswer: "A mix of a primary and secondary color" },
      { questionText: "What is 'hue'?", answerOptions: ["The brightness of a color", "The pure color itself", "The darkness of a color", "How much white is in a color"], correctAnswer: "The pure color itself" },
      { questionText: "Which color has the longest wavelength?", answerOptions: ["Violet", "Blue", "Green", "Red"], correctAnswer: "Red" },
      { questionText: "What color is 'chartreuse'?", answerOptions: ["A shade of red", "A shade of blue", "A yellow-green color", "A shade of purple"], correctAnswer: "A yellow-green color" },
      { questionText: "The color 'sepia' makes a photo look...", answerOptions: ["Black and white", "Very colorful", "Blueish", "Old and brownish"], correctAnswer: "Old and brownish" },
      { questionText: "What are complementary colors?", answerOptions: ["Colors that are similar", "Colors opposite on the color wheel", "Colors that are warm", "Colors that are cool"], correctAnswer: "Colors opposite on the color wheel" },
      { questionText: "If a shirt absorbs all colors of light, what color is it?", answerOptions: ["White", "Black", "Red", "Blue"], correctAnswer: "Black" },
    ],
    5: [
      { questionText: "What is the CMYK color model used for?", answerOptions: ["Digital screens", "Printing", "Painting", "Lighting"], correctAnswer: "Printing" },
      { questionText: "In the RGB color model, what does (255, 0, 0) represent?", answerOptions: ["Pure Green", "Pure Blue", "Pure Red", "White"], correctAnswer: "Pure Red" },
      { questionText: "What color is 'indigo' similar to?", answerOptions: ["A light green", "A bright yellow", "A deep blue-purple", "A reddish-orange"], correctAnswer: "A deep blue-purple" },
      { questionText: "The study of the effects of colors on human behavior is called...", answerOptions: ["Color Theory", "Chromatics", "Color Psychology", "Art History"], correctAnswer: "Color Psychology" },
      { questionText: "What does 'achromatic' mean?", answerOptions: ["Having all colors", "Being without color", "Being a primary color", "Being a secondary color"], correctAnswer: "Being without color" },
      { questionText: "Which artist is famous for his 'Blue Period'?", answerOptions: ["Van Gogh", "Monet", "Picasso", "Da Vinci"], correctAnswer: "Picasso" },
      { questionText: "What is an 'analogous' color scheme?", answerOptions: ["Colors opposite on the color wheel", "Colors that are next to each other on the color wheel", "Only one color", "Only black and white"], correctAnswer: "Colors that are next to each other on the color wheel" },
      { questionText: "The term 'ultramarine' refers to a deep shade of which color?", answerOptions: ["Red", "Green", "Yellow", "Blue"], correctAnswer: "Blue" },
      { questionText: "What pigment was historically made from grinding a precious stone?", answerOptions: ["Ochre (from clay)", "Umber (from earth)", "Lapis Lazuli (for blue)", "Carmine (from insects)"], correctAnswer: "Lapis Lazuli (for blue)" },
      { questionText: "What does it mean if a color is 'iridescent'?", answerOptions: ["It is very dark", "It glows in the dark", "It changes color depending on the angle", "It is a single, flat color"], correctAnswer: "It changes color depending on the angle" },
    ],
  },
  animals: {
    1: [
      { questionText: "What sound does a cat make?", answerOptions: ["Woof", "Meow", "Moo", "Oink"], correctAnswer: "Meow" },
      { questionText: "Which animal says 'Moo'?", answerOptions: ["Dog", "Cat", "Cow", "Pig"], correctAnswer: "Cow" },
      { questionText: "Which animal lives in the water?", answerOptions: ["Bird", "Fish", "Lion", "Monkey"], correctAnswer: "Fish" },
      { questionText: "Which animal has a long trunk?", answerOptions: ["Elephant", "Giraffe", "Zebra", "Tiger"], correctAnswer: "Elephant" },
      { questionText: "What does a dog say?", answerOptions: ["Meow", "Oink", "Woof", "Hiss"], correctAnswer: "Woof" },
      { questionText: "Which animal is the 'King of the Jungle'?", answerOptions: ["Monkey", "Elephant", "Lion", "Snake"], correctAnswer: "Lion" },
      { questionText: "Which animal likes to eat bananas?", answerOptions: ["Dog", "Cat", "Fish", "Monkey"], correctAnswer: "Monkey" },
      { questionText: "What animal gives us milk?", answerOptions: ["Chicken", "Cow", "Sheep", "Goat"], correctAnswer: "Cow" },
      { questionText: "Which animal can fly?", answerOptions: ["Dog", "Fish", "Bird", "Cat"], correctAnswer: "Bird" },
      { questionText: "Which animal has black and white stripes?", answerOptions: ["Tiger", "Lion", "Zebra", "Giraffe"], correctAnswer: "Zebra" },
    ],
    2: [
      { questionText: "Where does a polar bear live?", answerOptions: ["In the jungle", "In the desert", "In the cold Arctic", "In the ocean"], correctAnswer: "In the cold Arctic" },
      { questionText: "What is a baby dog called?", answerOptions: ["Kitten", "Puppy", "Cub", "Calf"], correctAnswer: "Puppy" },
      { questionText: "Which of these is NOT a farm animal?", answerOptions: ["Cow", "Chicken", "Pig", "Tiger"], correctAnswer: "Tiger" },
      { questionText: "What do bees make?", answerOptions: ["Milk", "Honey", "Juice", "Bread"], correctAnswer: "Honey" },
      { questionText: "Which animal is a reptile?", answerOptions: ["Bird", "Fish", "Snake", "Dog"], correctAnswer: "Snake" },
      { questionText: "How many legs does a spider have?", answerOptions: ["4", "6", "8", "10"], correctAnswer: "8" },
      { questionText: "What is a group of lions called?", answerOptions: ["A flock", "A herd", "A pride", "A school"], correctAnswer: "A pride" },
      { questionText: "Which animal is nocturnal (sleeps during the day)?", answerOptions: ["Cow", "Owl", "Chicken", "Dog"], correctAnswer: "Owl" },
      { questionText: "What is a baby cat called?", answerOptions: ["Puppy", "Kitten", "Cub", "Foal"], correctAnswer: "Kitten" },
      { questionText: "An animal that eats only plants is a...", answerOptions: ["Carnivore", "Herbivore", "Omnivore", "Insectivore"], correctAnswer: "Herbivore" },
    ],
    3: [
      { questionText: "Which animal is the largest mammal on Earth?", answerOptions: ["Elephant", "Blue Whale", "Giraffe", "Shark"], correctAnswer: "Blue Whale" },
      { questionText: "What is a female deer called?", answerOptions: ["Stag", "Buck", "Doe", "Fawn"], correctAnswer: "Doe" },
      { questionText: "Which animal can change its color?", answerOptions: ["Zebra", "Chameleon", "Hippo", "Penguin"], correctAnswer: "Chameleon" },
      { questionText: "What is a group of fish called?", answerOptions: ["A herd", "A flock", "A school", "A colony"], correctAnswer: "A school" },
      { questionText: "Which bird cannot fly?", answerOptions: ["Eagle", "Sparrow", "Ostrich", "Parrot"], correctAnswer: "Ostrich" },
      { questionText: "An animal that eats both plants and meat is an...", answerOptions: ["Carnivore", "Herbivore", "Omnivore", "Piscivore"], correctAnswer: "Omnivore" },
      { questionText: "What is the fastest land animal?", answerOptions: ["Lion", "Horse", "Cheetah", "Gazelle"], correctAnswer: "Cheetah" },
      { questionText: "How do snakes smell?", answerOptions: ["With their nose", "With their tongue", "With their ears", "They can't smell"], correctAnswer: "With their tongue" },
      { questionText: "What is a baby kangaroo called?", answerOptions: ["A joey", "A calf", "A pup", "A kit"], correctAnswer: "A joey" },
      { questionText: "Which animal sleeps hanging upside down?", answerOptions: ["Monkey", "Bird", "Bat", "Squirrel"], correctAnswer: "Bat" },
    ],
    4: [
      { questionText: "Which mammal can fly?", answerOptions: ["Flying squirrel", "Bat", "Bird", "Sugar glider"], correctAnswer: "Bat" },
      { questionText: "What is the process of an animal sleeping through the winter called?", answerOptions: ["Hibernation", "Estivation", "Migration", "Gestation"], correctAnswer: "Hibernation" },
      { questionText: "Which insect is known for its metamorphosis from a caterpillar?", answerOptions: ["Bee", "Ant", "Butterfly", "Grasshopper"], correctAnswer: "Butterfly" },
      { questionText: "What is the hard outer covering of an insect called?", answerOptions: ["Skin", "Shell", "Exoskeleton", "Fur"], correctAnswer: "Exoskeleton" },
      { questionText: "Which animal is known for building dams?", answerOptions: ["Otter", "Beaver", "Muskrat", "Raccoon"], correctAnswer: "Beaver" },
      { questionText: "What is a marsupial?", answerOptions: ["An animal that lays eggs", "An animal with a pouch", "An animal that lives underground", "A reptile"], correctAnswer: "An animal with a pouch" },
      { questionText: "Which animal has the longest neck?", answerOptions: ["Ostrich", "Giraffe", "Camel", "Llama"], correctAnswer: "Giraffe" },
      { questionText: "What is the scientific name for the study of animals?", answerOptions: ["Botany", "Geology", "Zoology", "Astronomy"], correctAnswer: "Zoology" },
      { questionText: "What class of animals do frogs belong to?", answerOptions: ["Reptiles", "Mammals", "Amphibians", "Fish"], correctAnswer: "Amphibians" },
      { questionText: "Which great ape is native to Asia?", answerOptions: ["Gorilla", "Chimpanzee", "Orangutan", "Bonobo"], correctAnswer: "Orangutan" }
    ],
    5: [
      { questionText: "What is echolocation, used by bats and dolphins?", answerOptions: ["A type of swimming", "Finding food using sound", "A way of sleeping", "Changing colors"], correctAnswer: "Finding food using sound" },
      { questionText: "What is a 'ruminant' animal?", answerOptions: ["An animal that chews its cud", "A nocturnal animal", "A cold-blooded animal", "An animal that flies"], correctAnswer: "An animal that chews its cud" },
      { questionText: "Which species is a 'keystone species' in its ecosystem?", answerOptions: ["Pigeon in a city", "Sea otter in a kelp forest", "Squirrel in a park", "Ant in a colony"], correctAnswer: "Sea otter in a kelp forest" },
      { questionText: "What is the difference between venom and poison?", answerOptions: ["There is no difference", "Venom is injected, poison is ingested", "Poison is stronger than venom", "Venom is from snakes, poison is from frogs"], correctAnswer: "Venom is injected, poison is ingested" },
      { questionText: "Which animal is a monotreme (a mammal that lays eggs)?", answerOptions: ["Kangaroo", "Platypus", "Koala", "Opossum"], correctAnswer: "Platypus" },
      { questionText: "What is the larval stage of a frog called?", answerOptions: ["Caterpillar", "Tadpole", "Nymph", "Pupa"], correctAnswer: "Tadpole" },
      { questionText: "The Great Barrier Reef is a massive ecosystem built by what tiny animal?", answerOptions: ["Fish", "Crabs", "Coral polyps", "Plankton"], correctAnswer: "Coral polyps" },
      { questionText: "What is bioluminescence?", answerOptions: ["The ability to fly", "The production of light by a living organism", "The ability to live underwater", "The process of changing color"], correctAnswer: "The production of light by a living organism" },
      { questionText: "What is the term for the seasonal movement of animals from one region to another?", answerOptions: ["Relocation", "Vacation", "Migration", "Commuting"], correctAnswer: "Migration" },
      { questionText: "What is sexual dimorphism?", answerOptions: ["When an animal has two mates", "When males and females of a species look different", "When an animal can live on land and water", "When an animal is born one gender and changes to another"], correctAnswer: "When males and females of a species look different" },
    ],
  },
  shapes: {
    1: [
      { questionText: "Which shape is round?", answerOptions: ["Square", "Circle", "Triangle", "Star"], correctAnswer: "Circle" },
      { questionText: "How many sides does a triangle have?", answerOptions: ["2", "3", "4", "5"], correctAnswer: "3" },
      { questionText: "Which shape has four equal sides?", answerOptions: ["Rectangle", "Circle", "Square", "Triangle"], correctAnswer: "Square" },
      { questionText: "What shape is a pizza slice?", answerOptions: ["Circle", "Square", "Triangle", "Oval"], correctAnswer: "Triangle" },
      { questionText: "What shape is a wheel?", answerOptions: ["Square", "Triangle", "Rectangle", "Circle"], correctAnswer: "Circle" },
      { questionText: "How many corners does a square have?", answerOptions: ["3", "4", "5", "6"], correctAnswer: "4" },
      { questionText: "What shape is a door?", answerOptions: ["Circle", "Rectangle", "Triangle", "Star"], correctAnswer: "Rectangle" },
      { questionText: "Which shape looks like a pointed hat?", answerOptions: ["Square", "Circle", "Cone", "Oval"], correctAnswer: "Cone" },
      { questionText: "What shape is a button on a shirt?", answerOptions: ["Circle", "Square", "Rectangle", "Star"], correctAnswer: "Circle" },
      { questionText: "What shape has 4 sides, with 2 long and 2 short?", answerOptions: ["Square", "Triangle", "Rectangle", "Circle"], correctAnswer: "Rectangle" },
    ],
    2: [
      { questionText: "What is a shape with 5 sides called?", answerOptions: ["Hexagon", "Pentagon", "Octagon", "Triangle"], correctAnswer: "Pentagon" },
      { questionText: "How many sides does a hexagon have?", answerOptions: ["5", "6", "7", "8"], correctAnswer: "6" },
      { questionText: "Which of these is a 3D shape?", answerOptions: ["Circle", "Square", "Cube", "Triangle"], correctAnswer: "Cube" },
      { questionText: "What 2D shape is the face of a cube?", answerOptions: ["Circle", "Square", "Triangle", "Rectangle"], correctAnswer: "Square" },
      { questionText: "What shape is a can of soup?", answerOptions: ["Cube", "Sphere", "Cylinder", "Cone"], correctAnswer: "Cylinder" },
      { questionText: "Which shape has no corners?", answerOptions: ["Square", "Triangle", "Circle", "Rectangle"], correctAnswer: "Circle" },
      { questionText: "What shape has 8 sides?", answerOptions: ["Pentagon", "Hexagon", "Octagon", "Nonagon"], correctAnswer: "Octagon" },
      { questionText: "What shape is an egg?", answerOptions: ["Circle", "Sphere", "Oval", "Cylinder"], correctAnswer: "Oval" },
      { questionText: "What 3D shape is a basketball?", answerOptions: ["Circle", "Sphere", "Cylinder", "Cube"], correctAnswer: "Sphere" },
      { questionText: "A pyramid has a square bottom. What shape are its sides?", answerOptions: ["Squares", "Triangles", "Circles", "Rectangles"], correctAnswer: "Triangles" },
    ],
    3: [
      { questionText: "What is the name for a polygon with ten sides?", answerOptions: ["Octagon", "Nonagon", "Decagon", "Dodecagon"], correctAnswer: "Decagon" },
      { questionText: "A shape with all sides and angles equal is called...", answerOptions: ["Irregular", "Regular", "Complex", "Simple"], correctAnswer: "Regular" },
      { questionText: "What is the 2D shape at the base of a cone?", answerOptions: ["Square", "Triangle", "Circle", "Point"], correctAnswer: "Circle" },
      { questionText: "Which of these shapes is symmetrical?", answerOptions: ["An irregular blob", "A perfect heart", "A slanted line", "A scribble"], correctAnswer: "A perfect heart" },
      { questionText: "A 'rhombus' is a tilted...?", answerOptions: ["Rectangle", "Circle", "Square", "Triangle"], correctAnswer: "Square" },
      { questionText: "How many vertices (corners) does a cube have?", answerOptions: ["4", "6", "8", "12"], correctAnswer: "8" },
      { questionText: "What is a 'trapezoid'?", answerOptions: ["A shape with 5 sides", "A shape with 4 sides, only two of which are parallel", "A tilted rectangle", "A shape with 6 sides"], correctAnswer: "A shape with 4 sides, only two of which are parallel" },
      { questionText: "What 3D shape is made of 6 square faces?", answerOptions: ["Rectangular Prism", "Cube", "Pyramid", "Sphere"], correctAnswer: "Cube" },
      { questionText: "What do you call the distance around a circle?", answerOptions: ["Area", "Diameter", "Radius", "Circumference"], correctAnswer: "Circumference" },
      { questionText: "How many faces does a triangular pyramid have?", answerOptions: ["3", "4", "5", "6"], correctAnswer: "4" },
    ],
    4: [
      { questionText: "What is the sum of angles in a triangle?", answerOptions: ["90 degrees", "180 degrees", "270 degrees", "360 degrees"], correctAnswer: "180 degrees" },
      { questionText: "What is the formula for the area of a rectangle?", answerOptions: ["length + width", "2 x (length + width)", "length x width", "length / width"], correctAnswer: "length x width" },
      { questionText: "If a circle's radius is 5, what is its diameter?", answerOptions: ["5", "10", "15", "2.5"], correctAnswer: "10" },
      { questionText: "What is a shape with four right angles and equal opposite sides?", answerOptions: ["Rhombus", "Trapezoid", "Rectangle", "Kite"], correctAnswer: "Rectangle" },
      { questionText: "What does 'congruent' mean?", answerOptions: ["Different size, same shape", "Same size, different shape", "Same size, same shape", "Different size, different shape"], correctAnswer: "Same size, same shape" },
      { questionText: "How many edges does a cube have?", answerOptions: ["6", "8", "10", "12"], correctAnswer: "12" },
      { questionText: "What is the line of symmetry?", answerOptions: ["A line that connects two corners", "A line dividing a shape into two identical halves", "The longest side of a shape", "The border of a shape"], correctAnswer: "A line dividing a shape into two identical halves" },
      { questionText: "What is a 'scalene' triangle?", answerOptions: ["All sides are equal", "Two sides are equal", "No sides are equal", "It has a right angle"], correctAnswer: "No sides are equal" },
      { questionText: "What do you call a 3D shape with two parallel circular bases?", answerOptions: ["Cone", "Sphere", "Cylinder", "Torus"], correctAnswer: "Cylinder" },
      { questionText: "What is an 'isosceles' triangle?", answerOptions: ["All sides are equal", "Two sides are equal", "No sides are equal", "It has a 90-degree angle"], correctAnswer: "Two sides are equal" },
    ],
    5: [
      { questionText: "What is the Pythagorean theorem used for?", answerOptions: ["Finding the area of a circle", "Finding the sides of a right-angled triangle", "Finding the volume of a cube", "Finding the angles of a triangle"], correctAnswer: "Finding the sides of a right-angled triangle" },
      { questionText: "A donut shape is called a...", answerOptions: ["Sphere", "Cylinder", "Torus", "Spheroid"], correctAnswer: "Torus" },
      { questionText: "How many diagonals does a pentagon have?", answerOptions: ["2", "5", "8", "10"], correctAnswer: "5" },
      { questionText: "What is Euler's formula for polyhedra?", answerOptions: ["V - E + F = 2", "V + E - F = 2", "E - V + F = 2", "V + E + F = 2"], correctAnswer: "V - E + F = 2" },
      { questionText: "What is a 'net' in geometry?", answerOptions: ["A 3D shape", "A type of graph", "A 2D pattern that can be folded into a 3D shape", "A tool for catching shapes"], correctAnswer: "A 2D pattern that can be folded into a 3D shape" },
      { questionText: "Which of the following is a Platonic solid?", answerOptions: ["Pyramid", "Cone", "Dodecahedron", "Cylinder"], correctAnswer: "Dodecahedron" },
      { questionText: "The cross-section of a sphere is always a...", answerOptions: ["Square", "Point", "Circle", "Oval"], correctAnswer: "Circle" },
      { questionText: "What is the value of Pi (π) approximately?", answerOptions: ["2.14", "3.14", "4.14", "1.61"], correctAnswer: "3.14" },
      { questionText: "A 'tessellation' is a pattern of shapes that...", answerOptions: ["Overlap each other", "Fit together with no gaps or overlaps", "Are all circles", "Create a 3D effect"], correctAnswer: "Fit together with no gaps or overlaps" },
      { questionText: "What do you call a polygon with 12 sides?", answerOptions: ["Decagon", "Hendecagon", "Dodecagon", "Icosagon"], correctAnswer: "Dodecagon" },
    ],
  },
};
